import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1731467921733 implements MigrationInterface {
    name = ' $npmConfigName1731467921733'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" text NOT NULL, "lastName" text NOT NULL, "email" text NOT NULL, "passwordHash" text NOT NULL, "phoneNumber" text, "userType" "public"."user_usertype_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "lastLogin" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organizationId" uuid, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization" ("orgId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "logo" text, "phone" text, "street" text, "city" text, "state" text, "zip" text, "category" text, "website" text, "superAdminId" uuid, "lastActive" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "status" text DEFAULT 'active', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_997ddda7c55b54ee3768a8cb407" PRIMARY KEY ("orgId"))`);
        await queryRunner.query(`CREATE TABLE "form_fields_option" ("form_fields_option_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "option" character varying(255) NOT NULL, "fieldFieldId" uuid, CONSTRAINT "PK_65572a1f7d177e436563ebc6642" PRIMARY KEY ("form_fields_option_id"))`);
        await queryRunner.query(`CREATE TABLE "form_fields" ("field_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "image" character varying, "question" character varying(255) NOT NULL, "type" character varying(50) NOT NULL, "sectionSectionId" uuid, CONSTRAINT "PK_791e05417236f98237ca86b5a1a" PRIMARY KEY ("field_id"))`);
        await queryRunner.query(`CREATE TABLE "section" ("section_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "formTemplateFormTemplateId" uuid, CONSTRAINT "PK_64bb5bb8f6931759fee65510d8e" PRIMARY KEY ("section_id"))`);
        await queryRunner.query(`CREATE TABLE "form_template" ("form_template_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "version" integer NOT NULL DEFAULT '1', "status" character varying(50) NOT NULL DEFAULT 'draft', "header_text" character varying, "header_image_url" character varying, "question_font_style" character varying, "question_text_color" character varying, "background_color" character varying, "header_image" character varying, "logo_image" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8b8c7ea7310175e49166d1622f7" PRIMARY KEY ("form_template_id"))`);
        await queryRunner.query(`CREATE TABLE "form" ("form_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "formTemplateFormTemplateId" uuid, CONSTRAINT "PK_ed84d8e98178872eb4ce8a3ebe7" PRIMARY KEY ("form_id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("categoryId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "user_id" uuid NOT NULL, CONSTRAINT "PK_8a300c5ce0f70ed7945e877a537" PRIMARY KEY ("categoryId"))`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP CONSTRAINT "PK_65572a1f7d177e436563ebc6642"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP COLUMN "form_fields_option_id"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP COLUMN "fieldFieldId"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "PK_791e05417236f98237ca86b5a1a"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP COLUMN "field_id"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP COLUMN "sectionSectionId"`);
        await queryRunner.query(`ALTER TABLE "section" DROP CONSTRAINT "PK_64bb5bb8f6931759fee65510d8e"`);
        await queryRunner.query(`ALTER TABLE "section" DROP COLUMN "section_id"`);
        await queryRunner.query(`ALTER TABLE "section" DROP COLUMN "formTemplateFormTemplateId"`);
        await queryRunner.query(`ALTER TABLE "form" DROP CONSTRAINT "PK_ed84d8e98178872eb4ce8a3ebe7"`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "form_id"`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "formTemplateFormTemplateId"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP CONSTRAINT "PK_8b8c7ea7310175e49166d1622f7"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "form_template_id"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "header_text"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "header_image_url"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "question_font_style"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "question_text_color"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "background_color"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "header_image"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "logo_image"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD "form_fields_option_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD CONSTRAINT "PK_65572a1f7d177e436563ebc6642" PRIMARY KEY ("form_fields_option_id")`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD "fieldFieldId" uuid`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD "field_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "PK_791e05417236f98237ca86b5a1a" PRIMARY KEY ("field_id")`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD "sectionSectionId" uuid`);
        await queryRunner.query(`ALTER TABLE "section" ADD "section_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "section" ADD CONSTRAINT "PK_64bb5bb8f6931759fee65510d8e" PRIMARY KEY ("section_id")`);
        await queryRunner.query(`ALTER TABLE "section" ADD "formTemplateFormTemplateId" uuid`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "form_template_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD CONSTRAINT "PK_8b8c7ea7310175e49166d1622f7" PRIMARY KEY ("form_template_id")`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "header_text" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "header_image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "question_font_style" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "question_text_color" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "background_color" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "header_image" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "logo_image" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form" ADD "form_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form" ADD CONSTRAINT "PK_ed84d8e98178872eb4ce8a3ebe7" PRIMARY KEY ("form_id")`);
        await queryRunner.query(`ALTER TABLE "form" ADD "formTemplateFormTemplateId" uuid`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD "formFieldsOptionId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP CONSTRAINT "PK_65572a1f7d177e436563ebc6642"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD CONSTRAINT "PK_5ad7a6939e9c22d424edaf01453" PRIMARY KEY ("form_fields_option_id", "formFieldsOptionId")`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD "field_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD "fieldId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "PK_791e05417236f98237ca86b5a1a"`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "PK_94f3bfc708ee57ede760e523008" PRIMARY KEY ("field_id", "fieldId")`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD "section_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "section" ADD "sectionId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "section" DROP CONSTRAINT "PK_64bb5bb8f6931759fee65510d8e"`);
        await queryRunner.query(`ALTER TABLE "section" ADD CONSTRAINT "PK_5cb70119be807e6331658adc6da" PRIMARY KEY ("section_id", "sectionId")`);
        await queryRunner.query(`ALTER TABLE "section" ADD "form_template_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form" ADD "formId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form" DROP CONSTRAINT "PK_ed84d8e98178872eb4ce8a3ebe7"`);
        await queryRunner.query(`ALTER TABLE "form" ADD CONSTRAINT "PK_4913a4e91532e38f99ad4c8f07d" PRIMARY KEY ("form_id", "formId")`);
        await queryRunner.query(`ALTER TABLE "form" ADD "form_template_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "formTemplateId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP CONSTRAINT "PK_8b8c7ea7310175e49166d1622f7"`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD CONSTRAINT "PK_7463f4dd6108e4c17e5f485f16f" PRIMARY KEY ("form_template_id", "formTemplateId")`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "headerText" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "headerImageUrl" text`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "questionFontStyle" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "questionTextColor" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "backgroundColor" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "headerImage" text`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "logoImage" text`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "category_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD "image" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "status" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_dfda472c0af7812401e592b6a61" FOREIGN KEY ("organizationId") REFERENCES "organization"("orgId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD CONSTRAINT "FK_f95ebca72fa6dcfe1489180dea8" FOREIGN KEY ("fieldFieldId") REFERENCES "form_fields"("field_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_37c0a9721e32005494327d57aa5" FOREIGN KEY ("sectionSectionId") REFERENCES "section"("section_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "section" ADD CONSTRAINT "FK_fb1a95e74705a03be7093959f9e" FOREIGN KEY ("formTemplateFormTemplateId") REFERENCES "form_template"("form_template_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form" ADD CONSTRAINT "FK_e19aa98b5d8d7e9a9fa52d2c074" FOREIGN KEY ("formTemplateFormTemplateId") REFERENCES "form_template"("form_template_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD CONSTRAINT "FK_9f9061bc2852674f23d77916e19" FOREIGN KEY ("field_id") REFERENCES "form_fields"("fieldId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_aba59d4fd998e34b736da0f59b3" FOREIGN KEY ("section_id") REFERENCES "section"("sectionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "section" ADD CONSTRAINT "FK_0d579e2c8d8f9a0b38fb48a6699" FOREIGN KEY ("form_template_id") REFERENCES "form_template"("formTemplateId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form" ADD CONSTRAINT "FK_c0b2d02ea98cc1984ee61842332" FOREIGN KEY ("form_template_id") REFERENCES "form_template"("formTemplateId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD CONSTRAINT "FK_0ca5481e0a49fe268661a372155" FOREIGN KEY ("category_id") REFERENCES "category"("categoryId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_6562e564389d0600e6e243d9604" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_6562e564389d0600e6e243d9604"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP CONSTRAINT "FK_0ca5481e0a49fe268661a372155"`);
        await queryRunner.query(`ALTER TABLE "form" DROP CONSTRAINT "FK_c0b2d02ea98cc1984ee61842332"`);
        await queryRunner.query(`ALTER TABLE "section" DROP CONSTRAINT "FK_0d579e2c8d8f9a0b38fb48a6699"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_aba59d4fd998e34b736da0f59b3"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP CONSTRAINT "FK_9f9061bc2852674f23d77916e19"`);
        await queryRunner.query(`ALTER TABLE "form" DROP CONSTRAINT "FK_e19aa98b5d8d7e9a9fa52d2c074"`);
        await queryRunner.query(`ALTER TABLE "section" DROP CONSTRAINT "FK_fb1a95e74705a03be7093959f9e"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_37c0a9721e32005494327d57aa5"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP CONSTRAINT "FK_f95ebca72fa6dcfe1489180dea8"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_dfda472c0af7812401e592b6a61"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "status" character varying(50) NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD "image" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "logoImage"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "headerImage"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "backgroundColor"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "questionTextColor"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "questionFontStyle"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "headerImageUrl"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "headerText"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP CONSTRAINT "PK_7463f4dd6108e4c17e5f485f16f"`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD CONSTRAINT "PK_8b8c7ea7310175e49166d1622f7" PRIMARY KEY ("form_template_id")`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "formTemplateId"`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "form_template_id"`);
        await queryRunner.query(`ALTER TABLE "form" DROP CONSTRAINT "PK_4913a4e91532e38f99ad4c8f07d"`);
        await queryRunner.query(`ALTER TABLE "form" ADD CONSTRAINT "PK_ed84d8e98178872eb4ce8a3ebe7" PRIMARY KEY ("form_id")`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "formId"`);
        await queryRunner.query(`ALTER TABLE "section" DROP COLUMN "form_template_id"`);
        await queryRunner.query(`ALTER TABLE "section" DROP CONSTRAINT "PK_5cb70119be807e6331658adc6da"`);
        await queryRunner.query(`ALTER TABLE "section" ADD CONSTRAINT "PK_64bb5bb8f6931759fee65510d8e" PRIMARY KEY ("section_id")`);
        await queryRunner.query(`ALTER TABLE "section" DROP COLUMN "sectionId"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP COLUMN "section_id"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "PK_94f3bfc708ee57ede760e523008"`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "PK_791e05417236f98237ca86b5a1a" PRIMARY KEY ("field_id")`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP COLUMN "fieldId"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP COLUMN "field_id"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP CONSTRAINT "PK_5ad7a6939e9c22d424edaf01453"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD CONSTRAINT "PK_65572a1f7d177e436563ebc6642" PRIMARY KEY ("form_fields_option_id")`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP COLUMN "formFieldsOptionId"`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "formTemplateFormTemplateId"`);
        await queryRunner.query(`ALTER TABLE "form" DROP CONSTRAINT "PK_ed84d8e98178872eb4ce8a3ebe7"`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "form_id"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "logo_image"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "header_image"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "background_color"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "question_text_color"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "question_font_style"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "header_image_url"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "header_text"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP CONSTRAINT "PK_8b8c7ea7310175e49166d1622f7"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP COLUMN "form_template_id"`);
        await queryRunner.query(`ALTER TABLE "section" DROP COLUMN "formTemplateFormTemplateId"`);
        await queryRunner.query(`ALTER TABLE "section" DROP CONSTRAINT "PK_64bb5bb8f6931759fee65510d8e"`);
        await queryRunner.query(`ALTER TABLE "section" DROP COLUMN "section_id"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP COLUMN "sectionSectionId"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "PK_791e05417236f98237ca86b5a1a"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP COLUMN "field_id"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP COLUMN "fieldFieldId"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP CONSTRAINT "PK_65572a1f7d177e436563ebc6642"`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" DROP COLUMN "form_fields_option_id"`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "logo_image" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "header_image" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "background_color" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "question_text_color" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "question_font_style" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "header_image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "header_text" character varying`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD "form_template_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD CONSTRAINT "PK_8b8c7ea7310175e49166d1622f7" PRIMARY KEY ("form_template_id")`);
        await queryRunner.query(`ALTER TABLE "form" ADD "formTemplateFormTemplateId" uuid`);
        await queryRunner.query(`ALTER TABLE "form" ADD "form_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form" ADD CONSTRAINT "PK_ed84d8e98178872eb4ce8a3ebe7" PRIMARY KEY ("form_id")`);
        await queryRunner.query(`ALTER TABLE "section" ADD "formTemplateFormTemplateId" uuid`);
        await queryRunner.query(`ALTER TABLE "section" ADD "section_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "section" ADD CONSTRAINT "PK_64bb5bb8f6931759fee65510d8e" PRIMARY KEY ("section_id")`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD "sectionSectionId" uuid`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD "field_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "PK_791e05417236f98237ca86b5a1a" PRIMARY KEY ("field_id")`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD "fieldFieldId" uuid`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD "form_fields_option_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form_fields_option" ADD CONSTRAINT "PK_65572a1f7d177e436563ebc6642" PRIMARY KEY ("form_fields_option_id")`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "form"`);
        await queryRunner.query(`DROP TABLE "form_template"`);
        await queryRunner.query(`DROP TABLE "section"`);
        await queryRunner.query(`DROP TABLE "form_fields"`);
        await queryRunner.query(`DROP TABLE "form_fields_option"`);
        await queryRunner.query(`DROP TABLE "organization"`);
        await queryRunner.query(`DROP TABLE "user"`);
    }

}
